# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(help_text='<textarea cols=100 rows=20 readonly>\n<!-- Post Image Start -->\n<div class="post-image margin-top-40 margin-bottom-40">\n   <img src="/media/img/" alt="image" width=\'500px\' height=\'500px\'>\n   <p>#</p>\n  </div>\n<!-- Post Image End -->\n\n----------------------------------------------------------------------\n\n <!-- Post Video Tutorial Start -->\n <div class="video-box margin-top-40 margin-bottom-40">\n  <div class="video-tutorial">\n   <a class="video-popup" href="#" title="#">\n   <img src="images/blog/#" alt="">\n   </a>\n  </div>\n <p>Integrate video on magnific popup for fast page load.</p>\n</div>\n<!-- Post Video Tutorial End -->\n\n-----------------------------------------------------------------------\n\n<!-- Post Blockquote Start -->\n  <div class="post-quote margin-top-40 margin-bottom-40">\n    <blockquote>#</blockquote>\n  </div>\n<!-- Post Blockquote End -->\n\n-------------------------------------------------------------------------\n\n<!-- Post Coding (SyntaxHighlighter) Start -->\n  <div class="margin-top-40 margin-bottom-40">\n   <pre class="brush: js">\n   /* Smooth Scroll */\n\n    $(\'a.smoth-scroll\').on("click", function (e) {\n      var anchor = $(this);\n      $(\'html, body\').stop().animate({\n      scrollTop: $(anchor.attr(\'href\')).offset().top - 50\n      }, 1000);\n      e.preventDefault();\n     });\n\n   /* Scroll To Top */\n\n   $(window).scroll(function(){\n     if ($(this).scrollTop() >= 500) {\n     $(\'.scroll-to-top\').fadeIn();\n     } else {\n     $(\'.scroll-to-top\').fadeOut();\n     }\n     });\n\n   $(\'.scroll-to-top\').click(function(){\n   $(\'html, body\').animate({scrollTop : 0},800);\n   return false;\n    });\n  </pre>\n </div>\n<!-- Post Coding (SyntaxHighlighter) End -->\n\n-------------------------------------------------------------------------------\n\n<!-- Post Image Gallery Start -->\n  <div class="row margin-top-40 margin-bottom-40">\n\n    <div class="col-md-4 col-sm-6 col-xs-12">\n      <a href="images/blog/7.jpg" class="image-popup" title="image Title">\n      <img src="images/blog/7.jpg" class="img-responsive" alt="">\n     </a>\n    </div>\n\n    <div class="col-md-4 col-sm-6 col-xs-12">\n      <a href="images/blog/5.jpg" class="image-popup" title="image Title">\n      <img src="images/blog/5.jpg" class="img-responsive" alt="">\n     </a>\n    </div>\n\n   <div class="col-md-4 col-sm-6 col-xs-12">\n     <a href="images/blog/6.jpg" class="image-popup" title="image Title">\n     <img src="images/blog/6.jpg" class="img-responsive" alt="">\n    </a>\n   </div>\n\n </div>\n<!-- Post Image Gallery End -->\n\n-----------------------------------------------------------------------------------\n\n<!-- Post Blockquote (Italic Style) Start -->\n  <blockquote class="margin-top-40 margin-bottom-40">\n    <p>###</p>\n   </blockquote>\n<!-- Post Blockquote (Italic Style) End -->\n\n------------------------------------------------------------------------------------\n\n<!-- Post List Style Start -->\n  <div class="list">\n   <ul>\n     <li></li>\n     <li></li>\n     <li></li>\n    </ul>\n   </div>\n\n\n  <div class="list list-style margin-top-40">\n   <ul>\n     <li></li>\n     <li></li>\n     <li></li>\n    </ul>\n   </div>\n\n\n  <div class="list list-style-2 margin-top-40">\n   <ul>\n     <li></li>\n     <li></li>\n     <li></li>\n    </ul>\n   </div>\n<!-- Post List Style End -->\n\n----------------------------------------------------------------------------------------\n\n<!-- Post Author Bio Box Start -->\n  <div class="about-author margin-top-70 margin-bottom-50">\n\n    <div class="picture">\n      <img src="images/blog/author.png" class="img-responsive" alt="">\n     </div>\n\n    <div class="c-padding">\n       <h3>Article By <a href="#" target="_blank" data-toggle="tooltip" data-placement="top" title="Visit Alex Website"></a></h3>\n       <p>You can use about author box when someone guest post on your blog.</p>\n      </div>\n    </div>\n<!-- Post Author Bio Box End -->\n</textarea>'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='intro',
            field=models.TextField(null=True),
        ),
    ]
